---
title: "2mimic_make_model_data"
author: "Andrew Hanson"
output:
  html_document:
    number_sections: true
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: true
params:
  write_data_mode: 'write'
---

```{r setup, include=FALSE}
# run this program
# Rscript -e "rmarkdown::render('2mimic_make_model_data.Rmd', params=list(write_data_mode='write'))"

library(dplyr)
library(tidyr)
library(sqldf)
library(arsenal)

row_limit <- -1

serial_minutes <- 15
min_serial_count <- 2*4
max_serial_count <- 24*4
```

```{r define_scaler_function}
scaler_data <- read.csv(file='../data/scaler_data/0053/qmain_train_scaler_data.csv')

qdata_scaler_function <- function(qdata, min_data=scaler_data[1,], max_data=scaler_data[3,], mean_data=scaler_data[2,]) {
  out <- qdata
  
  for(var in names(min_data)) {
    if(var %in% names(out)) {
      out[[var]][is.na(out[[var]])] <- mean_data[[var]]
      out[[var]] <- (out[[var]] - min_data[[var]]) / (max_data[[var]] - min_data[[var]])
    }
  }
  
  return(out)
}
```

```{r demo_data}
demo <- read.csv(file='./derived/v4/demo.csv', nrows=row_limit); dim(demo)

demo <- demo %>%
  mutate(
    intime = as.POSIXct(intime), 
    outtime = as.POSIXct(outtime),
    preiculos = if_else(preiculos <= 0, 0, preiculos),
    lpre_icu_days = log(preiculos + 0.001)
  ) %>%
  distinct()

demo <- demo %>%
  mutate(
    hosp_death = hospital_expire_flag,
    hosp_spdttm = dischtime,
    hosp_days = round(as.numeric(difftime(hosp_spdttm, admittime, units='days')), digits=3),
    prlos_death = case_when(
      hosp_death == 1 ~ 1,
      as.numeric(difftime(outtime, intime, units='days')) > 14 ~ 1,
      TRUE ~ 0
    ),
    male = if_else(gender == 'F', 0, 1)
  )
  
demo <- demo %>%
  rename(
    surg = surgical, transp = transplant, charlson_score = charlson_comorbidity_index, htn_hist = hypertension,
    mi_hist = myocardial_infarct, chf_hist = congestive_heart_failure, pvd_hist = peripheral_vascular_disease,
    asthma_hist = asthma, ild_hist = ild, connective_tissue_disease_hist = ctd, 
    dementia_hist = dementia, chronic_pulmonary_disease_hist = chronic_pulmonary_disease, dm_hist = diabetes_without_cc, 
    pud_hist = peptic_ulcer_disease, cirr_mild_liver_disease_hist = mild_liver_disease, 
    hemiplegia_paraplegia_hist = paraplegia, mod_sev_kidney_disease_hist = renal_disease,
    dm_complications_hist = diabetes_with_cc, cancer_tumor_hist = malignant_cancer, 
    mod_sev_liver_disease_hist = severe_liver_disease, metastatic_cancer_hist = metastatic_solid_tumor,
    aids_hist = aids, copd_hist = copd, leukemia_hist = leukemia, lymphoma_hist = lymphoma, cva_hist = cva
  ) %>%
  dplyr::select(
    subject_id, hadm_id, stay_id, intime, outtime, admittime, dischtime,
    age, male, lpre_icu_days, bmi, charlson_score, surg, transp, height, weight, htn_hist, mi_hist, chf_hist, pvd_hist, dementia_hist,
    cva_hist, copd_hist, asthma_hist, ild_hist, chronic_pulmonary_disease_hist, connective_tissue_disease_hist, dm_hist, pud_hist, 
    cirr_mild_liver_disease_hist, hemiplegia_paraplegia_hist,
    mod_sev_kidney_disease_hist, dm_complications_hist, cancer_tumor_hist, leukemia_hist, lymphoma_hist, mod_sev_liver_disease_hist,
    metastatic_cancer_hist, aids_hist, hosp_death, prlos_death
  )
```

```{r expand_qdemo}
qdemo <- demo %>%
  mutate(
    start_dttm = intime - as.numeric(format(intime, format="%M"))*60
  ) %>%
  rowwise() %>%
  mutate(subject_id, intime, outtime, dttm = list(start_dttm + seq(0, 48*3600, by = serial_minutes*60))) %>%
  unnest(dttm) %>%
  ungroup() %>%
  filter(
    intime <= dttm & dttm <= outtime & dttm <= intime + 24*3600
  ) %>%
  dplyr::select(
    subject_id, intime, outtime, dttm
  )

qdemo <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  mutate(
    id = 1:n()
  )

qdemo <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  group_by(subject_id, intime) %>%
  mutate(
    row_id = 1:n()
  ) %>%
  ungroup()

# drop those who do not have a minimum count of serial rows
tmp <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  group_by(subject_id, intime) %>%
  mutate(
    count = n()
  ) %>%
  slice_head(n=1) %>%
  dplyr::select(
    subject_id, intime, count
  )
  
tmp <- tmp %>%
  filter(
    count >= min_serial_count
  ) %>%
  dplyr::select(
    -count
  )

qdemo <- qdemo %>%
  inner_join(tmp, c('subject_id','intime'))

qdemo <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  group_by(subject_id, intime) %>%
  slice_head(n = max_serial_count) %>%
  ungroup()
```

```{r inicu_flag}
qdemo <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  mutate(
    inicu = if_else(intime <= dttm & dttm < outtime, 1, 0)
  ) %>%
  dplyr::select(
    subject_id, intime, dttm, id, row_id, inicu
  )
```

```{r vitals_data}
vitals <- read.csv(file='./derived/v4/vitals.csv', nrows=row_limit)

vitals <- vitals %>%
  mutate(
    charttime = as.POSIXct(charttime)
  )
```

```{r check_vitals_data}
vitals <- vitals %>%
  pivot_longer(cols=peep:rr, names_to = 'chartname', values_to = 'chartvalue') %>%
  filter(!is.na(chartvalue))

tmp <- demo %>%
  dplyr::select(
    subject_id, hadm_id, stay_id, intime, outtime
  )

vitals <- vitals %>%
  inner_join(tmp, 'subject_id', relationship='many-to-many')

vitals <- vitals %>%
  filter(intime - 6*3600 <= charttime & charttime <= intime + 7*24*3600)

vitals <- vitals %>%
  mutate(
    chartname = toupper(chartname)
  )
```

```{r join_vitals_data}
vitals_list <- c("peep", "tidal_vol", "map", "hr", "fio2", "spo2", "temp", "rr")

tmp <- qdemo %>%
  mutate(
    prior_dttm = dttm - 15*60
  ) %>%
  dplyr::select(
    subject_id, intime, dttm, prior_dttm
  )

tmp <- tmp %>%
  inner_join(
    dplyr::select(vitals, subject_id, charttime, chartname, chartvalue), join_by(subject_id, prior_dttm<charttime, dttm>=charttime)
  ); dim(tmp)

tmp <- tmp %>%
  dplyr::select(
    subject_id, intime, dttm, charttime, chartname, chartvalue
  ) %>%
  distinct(); dim(tmp)

tmp <- tmp %>%
  filter(
    chartname %in% toupper(vitals_list)
  ); dim(tmp)

tmp <- tmp %>%
  arrange(subject_id, intime, dttm, chartname, charttime) %>%
  group_by(subject_id, intime, dttm, chartname) %>%
  slice_tail(n=1) %>%
  ungroup(); dim(tmp)

tmp <- tmp %>%
  mutate(
    chartname = tolower(chartname)
  ) %>%
  dplyr::select(
    -charttime
  ) %>%
  pivot_wider(id_cols = subject_id:dttm, names_from = chartname, values_from = chartvalue)

qdemo <- qdemo %>%
  left_join(tmp, join_by(subject_id, intime, dttm))
```

```{r labs_data}
labs <- read.csv(file='./derived/v4/labs.csv', nrows=row_limit)

labs <- labs %>%
  mutate(
    charttime = as.POSIXct(charttime)
  )
```

```{r check_labs_data}
labs <- labs %>%
  pivot_longer(cols=glucose:ast, names_to = 'chartname', values_to = 'chartvalue') %>%
  filter(!is.na(chartvalue))

tmp <- demo %>%
  dplyr::select(
    subject_id, hadm_id, stay_id, intime, outtime
  )

labs <- labs %>%
  inner_join(tmp, c('subject_id','hadm_id'), relationship='many-to-many')

labs <- labs %>%
  filter(intime - 6*3600 <= charttime & charttime <= intime + 7*24*3600)

labs <- labs %>%
  mutate(
    chartname = toupper(chartname)
  )
```

```{r join_labs_data}
# last before admission
labs_list <- c("glucose", "hgb", "potassium", "sodium", "platelet", "hct", "ph", "creatinine", "wbc", "bun",
               "hco3", "paco2", "pao2", "lactate", "inr", "anion_gap", "ptt", "ast")

labs1 <- qdemo %>%
  mutate(
    prior_dttm = dttm - 6*3600
  ) %>%
  arrange(subject_id, intime, dttm) %>%
  group_by(subject_id, intime) %>%
  slice_head(n=1) %>%
  ungroup() %>%
  dplyr::select(
    subject_id, intime, dttm, prior_dttm
  )

labs1 <- labs1 %>%
  inner_join(
    dplyr::select(labs, subject_id, charttime, chartname, chartvalue), join_by(subject_id, prior_dttm<charttime, dttm>=charttime)
  ); dim(labs1)

labs1 <- labs1 %>%
  dplyr::select(
    subject_id, intime, dttm, charttime, chartname, chartvalue
  ) %>%
  distinct(); dim(labs1)

labs1 <- labs1 %>%
  filter(
    chartname %in% toupper(labs_list)
  ); dim(labs1)

labs1 <- labs1 %>%
  arrange(subject_id, intime, dttm, chartname, charttime) %>%
  group_by(subject_id, intime, dttm, chartname) %>%
  slice_tail(n=1) %>%
  ungroup(); dim(labs1)

labs1 <- labs1 %>%
  mutate(
    chartname = tolower(chartname)
  ) %>%
  dplyr::select(
    -charttime
  ) %>%
  pivot_wider(id_cols = subject_id:dttm, names_from = chartname, values_from = chartvalue)

# serial data
tmp <- qdemo %>%
  mutate(
    prior_dttm = dttm - 15*60
  ) %>%
  dplyr::select(
    subject_id, intime, dttm, prior_dttm
  )

tmp <- tmp %>%
  inner_join(
    dplyr::select(labs, subject_id, charttime, chartname, chartvalue), join_by(subject_id, prior_dttm<charttime, dttm>=charttime)
  ); dim(tmp)

tmp <- tmp %>%
  dplyr::select(
    subject_id, intime, dttm, charttime, chartname, chartvalue
  ) %>%
  distinct(); dim(tmp)

tmp <- tmp %>%
  filter(
    chartname %in% toupper(labs_list)
  ); dim(tmp)

tmp <- tmp %>%
  arrange(subject_id, intime, dttm, chartname, charttime) %>%
  group_by(subject_id, intime, dttm, chartname) %>%
  slice_tail(n=1) %>%
  ungroup(); dim(tmp)

tmp <- tmp %>%
  mutate(
    chartname = tolower(chartname)
  ) %>%
  dplyr::select(
    -charttime
  ) %>%
  pivot_wider(id_cols = subject_id:dttm, names_from = chartname, values_from = chartvalue)

qdemo <- qdemo %>%
  left_join(tmp, join_by(subject_id, intime, dttm))

qdemo <- qdemo %>%
  left_join(labs1, join_by(subject_id, intime, row_id))

qdemo <- qdemo %>%
  mutate(
    , glucose = coalesce(glucose.x, glucose.y)
    , hgb = coalesce(hgb.x, hgb.y)
    , potassium = coalesce(potassium.x, potassium.y)
    , sodium = coalesce(sodium.x, sodium.y)
    , platelet = coalesce(platelet.x, platelet.y)
    , hct = coalesce(hct.x, hct.y)
    , ph = coalesce(ph.x, ph.y)
    , creatinine = coalesce(creatinine.x, creatinine.y)
    , wbc = coalesce(wbc.x, wbc.y)
    , bun = coalesce(bun.x, bun.y)
    , hco3 = coalesce(hco3.x, hco3.y)
    , paco2 = coalesce(paco2.x, paco2.y)
    , pao2 = coalesce(pao2.x, pao2.y)
    , lactate = coalesce(lactate.x, lactate.y)
    , inr = coalesce(inr.x, inr.y)
    , anion_gap = coalesce(anion_gap.x, anion_gap.y)
    , ptt = coalesce(ptt.x, ptt.y)
    , ast = coalesce(ast.x, ast.y)
    ) %>%
    dplyr::select(
      -ends_with('.x'), -ends_with('.y')
    )
```

```{r gcs}
gcs <- read.csv(file='./derived/v4/gcs.csv', nrows=row_limit)

gcs <- gcs %>%
  mutate(
    charttime = as.POSIXct(charttime)
  ) %>%
  dplyr::select(
    subject_id, charttime, gcs
  )

tmp <- qdemo %>%
  mutate(
    prior_dttm = dttm - 15*60
  ) %>%
  dplyr::select(
    subject_id, intime, dttm, prior_dttm
  )

tmp <- tmp %>%
  inner_join(gcs, join_by(subject_id, prior_dttm<charttime, dttm>charttime))

tmp <- tmp %>%
  arrange(subject_id, intime, dttm, charttime) %>%
  group_by(subject_id, intime, dttm) %>%
  slice_tail(n=1) %>%
  ungroup() %>%
  dplyr::select(
    subject_id, intime, dttm, gcs
  )

qdemo <- qdemo %>%
  left_join(tmp, join_by(subject_id, intime, dttm))
```

```{r cpn}
cpn <- read.csv(file='./derived/v4/cpn.csv')

tmp <- cpn %>%
  inner_join(
    dplyr::select(qdemo, subject_id, dttm), 'subject_id', relationship='many-to-many'
  ) %>%
  filter(
    starttime <= dttm & dttm <= endtime
  )

tmp <- tmp %>%
  mutate(
    cpn = 1
  ) %>%
  dplyr::select(
    subject_id, dttm, cpn
  ) %>%
  distinct()

qdemo <- qdemo %>%
  left_join(tmp, c('subject_id','dttm')) %>%
  replace_na(list(cpn = 0))
```

```{r vasoactives}
vasos <- read.csv(file='./derived/v4/vasoactives.csv', nrows=row_limit)
```

```{r vasoactives_flags}
tmp <- vasos %>%
  mutate(
    starttime = as.POSIXct(starttime), 
    endtime = as.POSIXct(endtime),
    med = toupper(med), 
    flag = 1
  ) %>%
  dplyr::select(
    stay_id, starttime, endtime, med, flag
  ) %>%
  distinct() %>%
  inner_join(
    distinct(dplyr::select(demo, stay_id, subject_id)), 'stay_id', relationship='many-to-many'
  ) %>%
  inner_join(
    distinct(dplyr::select(qdemo, subject_id, dttm)), 'subject_id', relationship='many-to-many'
  )

tmp <- tmp %>%
  filter(
    starttime <= dttm & dttm < endtime
  ) %>%
  dplyr::select(
    subject_id, dttm, med, flag
  ) %>%
  distinct()

tmp <- tmp %>%
  pivot_wider(id_cols=subject_id:dttm, names_from = med, values_from = flag)

qdemo <- qdemo %>% 
  left_join(tmp, c('subject_id','dttm')) %>%
  replace_na(list(DOBUTAMINE = 0, NOREPINEPHRINE = 0, EPINEPHRINE = 0, VASOPRESSIN = 0))
```

```{r ringers_lactate}
ringers_lactate <- read.csv('./derived/v4/ringers_lactate.csv') %>%
  mutate(
    starttime = as.POSIXct(starttime), 
    endtime = as.POSIXct(endtime)
  )

tmp <- ringers_lactate %>%
  mutate(
    endtime = case_when(
      ordercategorydescription != 'Continuous IV' ~ starttime + 3600,
      TRUE ~ endtime
    )
  )

tmp <- tmp %>%
  mutate(
    ck = ((as.numeric(endtime) - as.numeric(starttime)) / 3600),
    fluid_rate = 0.25 * round(amount / ((as.numeric(endtime) - as.numeric(starttime)) / 3600), digits=3)
  )

tmp <- tmp %>%
  inner_join(
    dplyr::select(qdemo, subject_id, dttm), 'subject_id', relationship='many-to-many'
  )

tmp <- tmp %>%
  filter(
    starttime <= dttm & dttm < endtime
  ) %>%
  group_by(subject_id, dttm) %>%
  mutate(
    lactring = sum(fluid_rate)
  ) %>%
  slice_head(n=1) %>%
  ungroup() %>%
  dplyr::select(
    subject_id, dttm, lactring
  )

qdemo <- qdemo %>%
  left_join(tmp, c('subject_id','dttm')) %>%
  replace_na(list(lactring = 0))
```

```{r ventilation}
vent <- read.csv(file='./derived/v4/ventilation.csv', nrows=row_limit)
```

```{r ventilation_flags}
tmp <- vent %>%
  filter(!is.na(ventilation_status)) %>%
  filter(ventilation_status != 'None') %>%
  mutate(
    starttime = as.POSIXct(starttime), 
    endtime = as.POSIXct(endtime),
    flag = 1
  ) %>%
  dplyr::select(
    stay_id, starttime, endtime, ventilation_status, flag
  ) %>%
  distinct()

tmp <- tmp %>%
  inner_join(
    distinct(dplyr::select(demo, stay_id, subject_id)), 'stay_id', relationship='many-to-many'
  )

tmp <- tmp %>%
  inner_join(
    distinct(dplyr::select(qdemo, subject_id, dttm)), 'subject_id', relationship='many-to-many'
  )

tmp <- tmp %>%
  filter(
    starttime <= dttm & dttm < endtime
  ) %>%
  dplyr::select(
    subject_id, dttm, ventilation_status, flag
  ) %>%
  distinct()

tmp <- tmp %>%
  pivot_wider(id_cols=subject_id:dttm, names_from = ventilation_status, values_from = flag) %>%
  replace_na(list(SupplementalOxygen = 0, InvasiveVent = 0, NonInvasiveVent = 0, HFNC = 0, Tracheostomy = 0))

tmp <- tmp %>%
  mutate(
    invasive = if_else(InvasiveVent == 1, 1, 0),
    noninvasive = if_else(invasive == 0 & NonInvasiveVent == 1, 1, 0),
    vtother = if_else(invasive == 0 & noninvasive == 0 & (SupplementalOxygen == 1 | HFNC == 1 | Tracheostomy == 1), 1, 0)
  ) %>%
  dplyr::select(
    subject_id, dttm, invasive, noninvasive, vtother
  )

qdemo <- qdemo %>%
  left_join(tmp, c('subject_id','dttm')) %>%
  replace_na(list(invasive = 0, noninvasive = 0, vtother = 0))
```

```{r pneumonia_flags}
qdemo <- qdemo %>%
  left_join(
    dplyr::select(demo, subject_id, hadm_id, stay_id, intime, age:pneumoniadttm), c('subject_id','intime')
  ) %>%
  mutate(
    pneumonia = case_when(
      !is.na(pneumoniadttm) & pneumoniadttm <= dttm ~ 1,
      TRUE ~ 0
    )
  ) %>%
  dplyr::select(
    -pneumoniadttm
  )
```

```{r admission_ids}
qdemo <- qdemo %>%
  mutate(
    ecmo = 0, 
    intinf = NA,
    pulm_edema = NA,
    pleural_eff = NA
  )

qdemo <- qdemo %>%
  mutate(
    ph = if_else(is.na(ph), NA, if_else(ph < 6.5, NA, if_else(ph > 8, NA, ph))),
    lactate = if_else(is.na(lactate), NA, if_else(lactate < 0, 0, lactate)),
    ast = if_else(is.na(ast), NA, if_else(ast < 0, 0, ast)),
    creatinine = if_else(is.na(creatinine), NA, if_else(creatinine > 50, NA, creatinine)),
    temp = if_else(is.na(temp), NA, if_else(temp < 26, NA, temp)),
    glucose = if_else(is.na(glucose), NA, if_else(glucose > 1500, NA, glucose)),
    anion_gap = if_else(is.na(anion_gap), NA, if_else(anion_gap < -5, -5, anion_gap)),
    hco3 = if_else(is.na(hco3), NA, if_else(hco3 < 0, NA, hco3)),
    tidal_vol = if_else(is.na(tidal_vol), NA, if_else(tidal_vol > 1500, NA, tidal_vol)),
    lactring = if_else(lactring>330, 330, lactring),
    intinf = if_else(intinf>220, 220, intinf)
  )

qdemo <- qdemo %>%
  mutate(
    last = log(ast + 0.1),
    lptt = log(ptt),
    linr = log(inr),
    llactate = log(lactate + 0.1),
    lpao2 = log(pao2),
    lpaco2 = log(paco2),
    lbun = log(bun),
    lcreatinine = log(creatinine),
    lwbc = log(wbc + 1),
    lglucose = log(glucose),
    lplatelet = log(platelet),
    lpotassium = log(potassium)
  )
```

```{r get_lvcf}
# looks like fio2 can be higher than .21 off vent, so leave fio2 as-is and set peep and tidal volume
# values off vent to 0, then store result in temporary file.  these are the values that will end up populating
# when patients are off vent
qdemo <- qdemo %>%
  mutate(
    peep = if_else(is.na(peep) & invasive == 0 & noninvasive == 0 & vtother == 0, 0, peep),
    tidal_vol = if_else(is.na(tidal_vol) & invasive == 0 & noninvasive == 0 & vtother == 0, 0, tidal_vol)
  )

tmp <- qdemo %>% 
  dplyr::select(
    subject_id, hadm_id, stay_id, row_id, fio2, tidal_vol, peep
  )

# set values off vent to missing so none of them get carried forward
qdemo <- qdemo %>%
  mutate(
    fio2 = if_else(invasive != 1 & noninvasive != 1 & vtother != 1, NA, fio2),
    tidal_vol = if_else(invasive != 1 & noninvasive != 1 & vtother != 1, NA, tidal_vol),
    peep = if_else(invasive != 1 & noninvasive != 1 & vtother != 1, NA, peep)
  )

qdemo <- qdemo %>%
  arrange(subject_id, intime, dttm) %>%
  group_by(subject_id, intime) %>%
  mutate(
    across(lglucose:gcs, ~vctrs::vec_fill_missing(.x, max_fill = 24))
  ) %>%
  ungroup()

# join fio2 (only observed values), tidal volumes and peep (both set to 0 in when non-ventilated)
qdemo <- qdemo %>%
  left_join(tmp, c('subject_id','hadm_id','stay_id','row_id'))

# when ventilated, we use the data with last values carried forward (allow carry forward), otherwise we use the 
# off-vent values for fio2 (only observed values) and tidal volume and peep (all set to 0) 
qdemo <- qdemo %>%
  mutate(
    fio2 = if_else(invasive == 1 | noninvasive == 1 | vtother == 1, fio2.x, fio2.y), # x has carried forward values, 
    tidal_vol = if_else(invasive == 1 | noninvasive == 1 | vtother == 1, tidal_vol.x, tidal_vol.y),
    peep = if_else(invasive == 1 | noninvasive == 1 | vtother == 1, peep.x, peep.y)
  ) %>%
  dplyr::select(
    -fio2.x, -fio2.y, -tidal_vol.x, -tidal_vol.y, -peep.x, -peep.y
  )
```

```{r}
# new data
qdemo_new <- qdemo %>%
  dplyr::select(
    subject_id, hadm_id, stay_id, dttm, row_id, inicu, peep, tidal_vol, map, hr, fio2, spo2, temp, rr, lglucose, hgb, lpotassium, 
    sodium, lplatelet, hct, ph, lcreatinine, lwbc, lbun, hco3, lpaco2, lpao2, llactate, linr, anion_gap, lptt, last, gcs, 
    ecmo, cpn, NOREPINEPHRINE, EPINEPHRINE, DOBUTAMINE, VASOPRESSIN, lactring, intinf, pulm_edema, pleural_eff, pneumonia, 
    invasive, noninvasive, vtother, age, male, lpre_icu_days, bmi, charlson_score, surg, transp, htn_hist, mi_hist, chf_hist, 
    pvd_hist, dementia_hist, cva_hist, copd_hist, asthma_hist, ild_hist, chronic_pulmonary_disease_hist, 
    connective_tissue_disease_hist, dm_hist, pud_hist, cirr_mild_liver_disease_hist, hemiplegia_paraplegia_hist, 
    mod_sev_kidney_disease_hist, dm_complications_hist, cancer_tumor_hist, leukemia_hist, lymphoma_hist, 
    mod_sev_liver_disease_hist, metastatic_cancer_hist, aids_hist, hosp_death, prlos_death
  ) %>%
  arrange(subject_id, hadm_id, stay_id, row_id)
```

```{r}
qdemo_new_scaled <- qdata_scaler_function(qdata=qdemo_new)

if (params$write_data_mode == 'write') {
  write.csv(qdemo_new_scaled, file='./derived/v4/qdemo_lvcf_scaled.csv', row.names=FALSE, na='')
}
```
