---
title: "Untitled"
author: "Andrew Hanson"
date: "2024-05-24"
output: html_document
---

```{r setup, include=FALSE}
# run in batch
# Rscript -e "rmarkdown::render('6mimicSummary.Rmd')"

knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(pROC)
```

```{r}
files <- system("find ./results/v3 | grep _predicted.csv", intern=TRUE)
files <- files[order(files)]

pred_names <- unlist(lapply(strsplit(files, '/', fixed=TRUE, perl=FALSE), FUN=function(x) x[[4]]))

pred_names <- unlist(lapply(strsplit(pred_names, '.', fixed=TRUE, perl=FALSE), function(x) x[[1]]))

names(files) <- pred_names

print(files)

for (i in 1:length(files)) {
  file <- files[[i]]
  
  tmp <- read.csv(file) %>%
    dplyr::select(
      admit_id, session_id, prlos_death, starts_with('yhat')
    )

  if (i == 1) {
    out <- tmp
  }
  else {
    out <- out %>% left_join(tmp, c('admit_id', 'session_id', 'prlos_death'))
  }
}

out <- out %>%
  rowwise() %>%
  mutate(
    yhat_merged_ensemble = (yhat_nn + yhat_merged_cnnsmall + yhat_merged_cnntiny + yhat_merged_lstmsmall + yhat_merged_lstmtiny)/5,
    yhat_nolvcf_ensemble = (yhat_nolvcf_cnnsmall + yhat_nolvcf_cnntiny + yhat_nolvcf_lstmsmall + yhat_nolvcf_lstmtiny)/4
  ) %>%
  ungroup()
  
dim(out)
head(out)

write.csv(out, './results/v3/ztest_predicteds_mimic.csv', row.names=FALSE)
```

# 12 hours

```{r}
out_list <- split(out, factor(out$session_id))

y <- out_list[['48']]$prlos_death

roc_list <- lapply(out_list[['48']], FUN=function(x) roc(y ~ x))

roc_list
```

# 24 hours

```{r}
y <- out_list[['96']]$prlos_death

roc_list <- lapply(out_list[['96']], FUN=function(x) roc(y ~ x))

roc_list
```
